function func1(){
    if(document.getElementById("p11").style.display==="none"){
        document.getElementById("p11").style.display="block";
        document.getElementById("p1").style.fontWeight="bold";
        document.getElementById("p2").style.fontWeight="normal";
        document.getElementById("p3").style.fontWeight="normal";
        document.getElementById("p4").style.fontWeight="normal";
        document.getElementById("p5").style.fontWeight="normal";
        document.getElementById("p22").style.display="none";
        document.getElementById("p33").style.display="none";
        document.getElementById("p44").style.display="none";
        document.getElementById("p55").style.display="none";
        document.getElementById("svg11").style.paddingRight="0px";
        document.getElementById("svg11").style.transform="rotate(180deg)";
        document.getElementById("svg22").style.transform="rotate(0deg)";
        document.getElementById("svg33").style.transform="rotate(0deg)";
        document.getElementById("svg44").style.transform="rotate(0deg)";
        document.getElementById("svg55").style.transform="rotate(0deg)";

    }
    else{
        document.getElementById("p11").style.display="none";
        document.getElementById("p1").style.fontWeight="normal";
        document.getElementById("p2").style.fontWeight="normal";
        document.getElementById("p3").style.fontWeight="normal";
        document.getElementById("p4").style.fontWeight="normal";
        document.getElementById("p5").style.fontWeight="normal";
        document.getElementById("svg11").style.transform="rotate(0deg)";
        document.getElementById("svg22").style.transform="rotate(0deg)";
        document.getElementById("svg33").style.transform="rotate(0deg)";
        document.getElementById("svg44").style.transform="rotate(0deg)";
        document.getElementById("svg55").style.transform="rotate(0deg)";
    }
}
function func2(){
    if(document.getElementById("p22").style.display==="none"){
        document.getElementById("p22").style.display="block";
        document.getElementById("p2").style.fontWeight="bold";
        document.getElementById("p1").style.fontWeight="normal";
        document.getElementById("p3").style.fontWeight="normal";
        document.getElementById("p4").style.fontWeight="normal";
        document.getElementById("p5").style.fontWeight="normal";
        document.getElementById("p11").style.display="none";
        document.getElementById("p33").style.display="none";
        document.getElementById("p44").style.display="none";
        document.getElementById("p55").style.display="none";
        document.getElementById("svg22").style.paddingRight="0px";
        document.getElementById("svg22").style.transform="rotate(180deg)";
        document.getElementById("svg11").style.transform="rotate(0deg)";
        document.getElementById("svg33").style.transform="rotate(0deg)";
        document.getElementById("svg44").style.transform="rotate(0deg)";
        document.getElementById("svg55").style.transform="rotate(0deg)";

    }
    else{
        document.getElementById("p22").style.display="none";
        document.getElementById("p1").style.fontWeight="normal";
        document.getElementById("p2").style.fontWeight="normal";
        document.getElementById("p3").style.fontWeight="normal";
        document.getElementById("p4").style.fontWeight="normal";
        document.getElementById("p5").style.fontWeight="normal";
        document.getElementById("svg22").style.transform="rotate(0deg)";
        document.getElementById("svg11").style.transform="rotate(0deg)";
        document.getElementById("svg33").style.transform="rotate(0deg)";
        document.getElementById("svg44").style.transform="rotate(0deg)";
        document.getElementById("svg55").style.transform="rotate(0deg)";
    }
}
function func3(){
    if(document.getElementById("p33").style.display==="none"){
        document.getElementById("p3").style.fontWeight="bold";
        document.getElementById("p1").style.fontWeight="normal";
        document.getElementById("p2").style.fontWeight="normal";
        document.getElementById("p4").style.fontWeight="normal";
        document.getElementById("p5").style.fontWeight="normal";
        document.getElementById("p33").style.display="block";
        document.getElementById("p22").style.display="none";
        document.getElementById("p11").style.display="none";
        document.getElementById("p44").style.display="none";
        document.getElementById("p55").style.display="none";
        document.getElementById("svg33").style.paddingRight="0px";
        document.getElementById("svg33").style.transform="rotate(180deg)";
        document.getElementById("svg11").style.transform="rotate(0deg)";
        document.getElementById("svg22").style.transform="rotate(0deg)";
        document.getElementById("svg44").style.transform="rotate(0deg)";
        document.getElementById("svg55").style.transform="rotate(0deg)";

    }
    else{
        document.getElementById("p33").style.display="none";
        document.getElementById("p1").style.fontWeight="normal";
        document.getElementById("p2").style.fontWeight="normal";
        document.getElementById("p3").style.fontWeight="normal";
        document.getElementById("p4").style.fontWeight="normal";
        document.getElementById("p5").style.fontWeight="normal";
        document.getElementById("svg11").style.transform="rotate(0deg)";
        document.getElementById("svg22").style.transform="rotate(0deg)";
        document.getElementById("svg33").style.transform="rotate(0deg)";
        document.getElementById("svg44").style.transform="rotate(0deg)";
        document.getElementById("svg55").style.transform="rotate(0deg)";
    }
}
function func4(){
    if(document.getElementById("p44").style.display==="none"){
        document.getElementById("p4").style.fontWeight="bold";
        document.getElementById("p1").style.fontWeight="normal";
        document.getElementById("p2").style.fontWeight="normal";
        document.getElementById("p3").style.fontWeight="normal";
        document.getElementById("p5").style.fontWeight="normal";
        document.getElementById("p44").style.display="block";
        document.getElementById("p22").style.display="none";
        document.getElementById("p33").style.display="none";
        document.getElementById("p11").style.display="none";
        document.getElementById("p55").style.display="none";
        document.getElementById("svg44").style.paddingRight="0px";
        document.getElementById("svg44").style.transform="rotate(180deg)";
        document.getElementById("svg55").style.transform="rotate(0deg)";
        document.getElementById("svg11").style.transform="rotate(0deg)";
        document.getElementById("svg22").style.transform="rotate(0deg)";
        document.getElementById("svg33").style.transform="rotate(0deg)";

    }
    else{
        document.getElementById("p44").style.display="none";
        document.getElementById("p1").style.fontWeight="normal";
        document.getElementById("p2").style.fontWeight="normal";
        document.getElementById("p3").style.fontWeight="normal";
        document.getElementById("p4").style.fontWeight="normal";
        document.getElementById("p5").style.fontWeight="normal";
        document.getElementById("svg11").style.transform="rotate(0deg)";
        document.getElementById("svg22").style.transform="rotate(0deg)";
        document.getElementById("svg33").style.transform="rotate(0deg)";
        document.getElementById("svg44").style.transform="rotate(0deg)";
        document.getElementById("svg55").style.transform="rotate(0deg)";
    }
}
function func5(){
    if(document.getElementById("p55").style.display==="none"){
        document.getElementById("p5").style.fontWeight="bold";
        document.getElementById("p1").style.fontWeight="normal";
        document.getElementById("p2").style.fontWeight="normal";
        document.getElementById("p3").style.fontWeight="normal";
        document.getElementById("p4").style.fontWeight="normal";
        document.getElementById("p55").style.display="block";
        document.getElementById("p22").style.display="none";
        document.getElementById("p33").style.display="none";
        document.getElementById("p44").style.display="none";
        document.getElementById("p11").style.display="none";
        document.getElementById("svg55").style.paddingRight="0px";
        document.getElementById("svg55").style.transform="rotate(180deg)";
        document.getElementById("svg11").style.transform="rotate(0deg)";
        document.getElementById("svg22").style.transform="rotate(0deg)";
        document.getElementById("svg33").style.transform="rotate(0deg)";
        document.getElementById("svg44").style.transform="rotate(0deg)";

    }
    else{
        document.getElementById("p55").style.display="none";
        document.getElementById("p1").style.fontWeight="normal";
        document.getElementById("p2").style.fontWeight="normal";
        document.getElementById("p3").style.fontWeight="normal";
        document.getElementById("p4").style.fontWeight="normal";
        document.getElementById("p5").style.fontWeight="normal";
        document.getElementById("svg11").style.transform="rotate(0deg)";
        document.getElementById("svg22").style.transform="rotate(0deg)";
        document.getElementById("svg33").style.transform="rotate(0deg)";
        document.getElementById("svg44").style.transform="rotate(0deg)";
        document.getElementById("svg55").style.transform="rotate(0deg)";
    }
}
